name: Publish documentation as docx

on:
  release:
    types: [ created, published ]

jobs:
  convert_md_to_docx:
    runs-on:  ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Make single .md
        run: python ./publish/combine.py
      - name: Convert to docx
        uses: docker://pandoc/latex:2.9
        with:
            args: ./publish/combined.md --reference-doc=./publish/reference.docx -o ./publish/docs.docx
      - name: Append to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./publish/docs.docx
          tags: false
          draft: true